# This is a basic workflow to help you get started with Actions
name: build_master_tag

# Push to docker hub if tag has been created for master branch
on:
  push:
    branches: [ master ]
    tags:
      - v*
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
#     env:
#       CI_REGISTRY: ${{ secrets.CI_REGISTRY }}
#       CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
#       CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
#       CI_REGISTRY_IMAGE: ${{ secrets.CI_REGISTRY_IMAGE }}
#       CI_COMMIT_SHORT_SHA: ${{ secrets.CI_COMMIT_SHORT_SHA }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set Env
      run: |
        echo ::set-env name=KANIKO_CACHE_REGISTRY::aquaveollc/helm-docker-cache
        echo ::set-env name=KANIKO_IMAGE::aquaveollc/helm-docker
    - name: Set Tag
      run: |
        echo ::set-env name=TAG::${GITHUB_REF:10}
    - name: Set Master Tag
      if: endsWith(github.ref, '/master')
      run: |
        echo ::set-env name=TAG::latest
    - name: Test Tag
      run: |
        echo $TAG
    - name: build tag
      uses: aevea/action-kaniko@v0.3.2
      with:
        # Docker registry where the image will be pushed
        registry: docker.io
        # Username used for authentication to the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password used for authentication to the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Image name
        image: $KANIKO_IMAGE
        # Image tag
        tag: $TAG
        # Enables build cache
        cache: false
        # Docker registry meant to be used as cache
        cache_registry: $KANIKO_CACHE_REGISTRY
        # Dockerfile filename
        build_file: ${{github.workspace}}/Dockerfile

