# This is a basic workflow to help you get started with Actions

name: kaniko_build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CI_REGISTRY: ${{ secrets.CI_REGISTRY }} 
      CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
      CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
      CI_REGISTRY_IMAGE: ${{ secrets.CI_REGISTRY_IMAGE }}
      CI_COMMIT_SHORT_SHA: ${{ secrets.CI_COMMIT_SHORT_SHA }}
      KANIKO_DOCKERFILE: Dockerfile
      KANIKO_CONTEXT:  ${{ secrets.KANIKO_CONTEXT }}
      KANIKO_DESTINATIONS: ${{ secrets.KANIKO_DESTINATIONS }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs a set of commands using the runners shell
    - name: Build Kaniko Image
      uses: aevea/action-kaniko@v0.3.2
    - name: Build Commit
      run: >
        export KANIKO_CMD="/kaniko/executor 
        --context $KANIKO_CONTEXT 
        --dockerfile $KANIKO_DOCKERFILE
        $(for DEST in $KANIKO_DESTINATIONS; do echo "--destination $DEST "; done)
        --cache=true
        --cache-repo $CI_REGISTRY_IMAGE/cache";
        echo $KANIKO_CMD;
        $KANIKO_CMD 
