# This is a basic workflow to help you get started with Actions

name: kaniko_build

# Controls when the action will run. Triggers the workflow on push or pull request
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
#     env:
#       CI_REGISTRY: ${{ secrets.CI_REGISTRY }}
#       CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
#       CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
#       CI_REGISTRY_IMAGE: ${{ secrets.CI_REGISTRY_IMAGE }}
#       CI_COMMIT_SHORT_SHA: ${{ secrets.CI_COMMIT_SHORT_SHA }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
#    - name: Set Env
#      run: |
#        echo ::set-env name=KANIKO_CACHE_REGISTRY::helm-docker/cache
#        echo ::set-env name=KANIKO_IMAGE::aquaveollc/helm-docker
#        echo ::set-env name=TAG::$(echo ${GITHUB_REF:10})
    - name: Dokcer Build and push to docker hub
      uses: opspresso/action-docker@master
      with:
        args: --docker
      env:
        # Username used for authentication to the Docker registry
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        # Password used for authentication to the Docker registry
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERFILE: "Dockerfile"
        IMAGE_NAME: "aquaveollc/helm-docker"
        # Image tag
        TAG_NAME: "v0.0.1"
        LATEST: "true"

